apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-pki-demo
spec:
  acme:
    caBundle: ### 
    privateKeySecretRef:
      name: acme-account-key
    server: https://pki-demo.home.arpa/acme/acme/directory
    solvers:
    - http01:
        ingress:
          class: nginx
          serviceType: ClusterIP
